Repository shivanshugarg12800/Algo_GT, pull requests merged in 2021-10, with the labels that each got.

#5 added contribution in DP folder
  C++/DP/minimumCount.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#6 Create ReverseAStack
  C++/Recursion/ReverseAStack
Labels: Hacktoberfest, hacktoberfest-accepted

#12 knapsack solution added
  C++/DP/knapsack.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#13 Create DecodeString
  C++/Recursion/DecodeString
Labels: Hacktoberfest, hacktoberfest-accepted

#10 Create IsPalindrome
  C++/Recursion/IsPalindrome
Labels: Hacktoberfest, hacktoberfest-accepted

#19 Create Pow(x, n)
  C++/Recursion/Pow(x, n)
Labels: Hacktoberfest, hacktoberfest-accepted

#28 #16 Solution to leetcode problem 1823
  C++/StacksQueues/1823_Find_the_Winner_of_the_Circular_Game.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#30 Create RecamansSequence
  C++/Recursion/RecamansSequence
Labels: Hacktoberfest, hacktoberfest-accepted

#32 Create DecimalToBinary
  C++/Recursion/DecimalToBinary
Labels: Hacktoberfest, hacktoberfest-accepted

#36 added in trees
  C++/Tree/8LInearizeTree.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#38 Create BinaryToGray
  C++/Recursion/BinaryToGray
Labels: Hacktoberfest, hacktoberfest-accepted

#46 Added python code for a few algorithms
  Python/.DS_Store
  Python/ArrayString/01_LongPressedName.py
  Python/ArrayString/02_containerWithMaximumWater.py
  Python/ArrayString/03_squaresOfSortedArray.py
  Python/ArrayString/04_NextGreaterElement3.py
  Python/ArrayString/05_majorityElement.py
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#42 Repository created for Binary_Search_Algorithm : Created for #26
  C++/ArrayString/48.Binary_Search_Algorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#39 Spiral matrix in c++ : Created Repository for #27
  C++/ArrayString/47. Print_Spiral_Matix
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#45 #34 174_Dungeon_Game_LeetCode.cpp
  C++/DP/174_Dungeon_Game_LeetCode.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#49 Create SmallerNumbers.java
  Java/ArrayString/45_SmallerNumbers.java
  Java/Recursion/FIndKthBitInNthString.java
Labels: Hacktoberfest, hacktoberfest-accepted

#51 Strassen's Matrix Multiplication
  Java/ArrayString/47_StrassenMult.java
Labels: Hacktoberfest, hacktoberfest-accepted

#54 Create PrintSubsets
  C++/Recursion/PrintSubsets
Labels: Hacktoberfest, hacktoberfest-accepted

#56 Create InterleavingStrings
  C++/Recursion/InterleavingStrings
Labels: Hacktoberfest, hacktoberfest-accepted

#58 Create QuickselectAlgorithm
  C++/Recursion/QuickselectAlgorithm
Labels: Hacktoberfest, hacktoberfest-accepted

#48 Update readme.md
  readme.md
Labels: Hacktoberfest, hacktoberfest-accepted

#68 FindKthBitInNthString
  Java/RecursionProblems/FindKthBitInNthString.java
Labels: Hacktoberfest, hacktoberfest-accepted, New Question
